export const CHANGE_INPUT_FIELD = "CHANGE_INPUT_FIELD";
export const CHANGE_BOX_DATA = "CHANGE_BOX_DATA";

export const GET_SCORES_PENDING = "GET_SCORES_PENDING";
export const GET_SCORES_FAILED = "GET_SCORES_FAILED";
export const GET_SCORES_SUCCESS = "GET_SCORES_SUCCESS";

export const LOGIN_USER_PENDING = "LOGIN_USER_PENDING";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER= "LOGOUT_USER";

export const CHANGE_EMAIL_FIELD = "CHANGE_EMAIL_FIELD";
export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD";

export const CHANGE_ROUTE = "CHANGE_ROUTE";